name: 'openID-Terraform'

on:
    push:
      branches: [ "main" ]
    pull_request:
 
permissions:
  id-token: write
  contents: read
  pull-requests: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: development
    defaults:
      run:
        shell: bash

    steps:
    - name: Create SSH Directory
      run: mkdir -p ~/.ssh

    - name: setup the public key
      run:  echo "${{ secrets.PUBLIC_KEY_NAME}}" > ~/.ssh/openid.pub && chmod 600 ~/.ssh/openid.pub


    - name: Configure aws credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::120666943157:role/openid-terrraform-gh-wf
        aws-region: us-east-1
    
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.6
    
    - name: Terraform Init
      run: cd examples && terraform init

    - name: Terraform Validate
      run:  cd examples && terraform validate -no-color

    - name: Terraform Plan
      run:  cd examples && terraform plan -input=false

      # On push to "main", deploy the Terraform infrastructure
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: cd examples && terraform apply -auto-approve -input=false